"""add test_violations table and attempt violation tracking

Revision ID: 675a7be99b8a
Revises: 202607150001
Create Date: 2026-08-03 11:04:38.954304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675a7be99b8a'
down_revision: Union[str, None] = '202607150001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add new values to notification_type_enum
    op.execute("ALTER TYPE notification_type_enum ADD VALUE IF NOT EXISTS 'test_violation'")
    op.execute("ALTER TYPE notification_type_enum ADD VALUE IF NOT EXISTS 'test_auto_ended'")

    attempt_ended_reason_enum = sa.Enum('completed', 'timeout', 'violation_limit', name='attempt_ended_reason_enum')
    attempt_ended_reason_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('violation_type', sa.Enum('tab_switch', 'copy_attempt', 'devtools', 'noise', 'face_away', 'no_face', 'multi_face', 'screenshot_attempt', name='violation_type_enum'), nullable=False),
    sa.Column('strike_number', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_violations_attempt_id'), 'test_violations', ['attempt_id'], unique=False)
    op.add_column('test_attempts', sa.Column('total_violation_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('test_attempts', sa.Column('ended_reason', attempt_ended_reason_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_attempts', 'ended_reason')
    op.drop_column('test_attempts', 'total_violation_count')
    op.drop_index(op.f('ix_test_violations_attempt_id'), table_name='test_violations')
    op.drop_table('test_violations')
    op.execute("DROP TYPE IF EXISTS attempt_ended_reason_enum")
    op.execute("DROP TYPE IF EXISTS violation_type_enum")
    # ### end Alembic commands ###
