"""add industry_type to companies and placement_type student_instructions to drives

Revision ID: ca54503eabb2
Revises: 874f955925c3
Create Date: 2026-08-09 16:34:22.138626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca54503eabb2'
down_revision: Union[str, None] = '874f955925c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('industry_type', sa.String(length=255), nullable=True))
    op.add_column('drives', sa.Column('placement_type', sa.String(length=100), nullable=True))
    op.add_column('drives', sa.Column('student_instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drives', 'student_instructions')
    op.drop_column('drives', 'placement_type')
    op.drop_column('companies', 'industry_type')
    # ### end Alembic commands ###
